---
include:
  - project: secrecy/ci-vault
    file: consul-template-vault.yml


stages:
  - prepare
  - secrets
  - build

maintain-vault:
  stage: prepare
  extends:
    - .vault_get_wrapping_url
  rules:
    - if: $MAINTAIN_VAULT

env-from-secrets:
  stage: secrets
  extends: [.vault_env]


variables:
  VAULT_ROLE: any
  VAULT_SECRETS_PATH: kv/gitlab2-epaas/data/${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAMESPACE_ID}/container_registry
  GIT_DEPTH: 5
  GIT_TERMINAL_PROMPT: 1
  REGISTRY: registry.s7corp.ru

  # Основной путь к репозиторию образов
  BASE_IMAGE_PATH: $REGISTRY/$CI_PROJECT_PATH

.build_tags:
  tags:
    - dind-epaas


# Стадия сборки образа
build_image:
  stage: build
  image: "$REGISTRY/epaas/common/buildah/stable:v1.31.0-mir"
  extends: [.build_tags]
  before_script:
    - curl -so /usr/share/pki/ca-trust-source/anchors/group-s7.crt http://ca.s7.ru/group-S7-ROOT-CA.crt
    - update-ca-trust
    - echo  ${USERNAME}
    - buildah login -u ${USERNAME} -p ${PASSWORD} ${REGISTRY}
  script:
    - echo "Determining environment..."
    - IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - if [ "$CI_COMMIT_TAG" ]; then
    - ENVIRONMENT="prod"
    - IMAGE_TAG=$CI_COMMIT_TAG
    - elif [ "$CI_COMMIT_REF_NAME" == "main" ]; then
    - ENVIRONMENT="uat"
    - else
    - ENVIRONMENT="dev"
    - fi
    - buildah pull ${BASE_IMAGE_PATH}/${ENVIRONMENT}:latest|| true
    - buildah bud --cache-from ${BASE_IMAGE_PATH}/${ENVIRONMENT}:latest
      -t ${BASE_IMAGE_PATH}/${ENVIRONMENT}:latest -t ${BASE_IMAGE_PATH}/${ENVIRONMENT}:${IMAGE_TAG} .
    - buildah push --retry 5 --retry-delay 10s ${BASE_IMAGE_PATH}/${ENVIRONMENT}:${IMAGE_TAG}
    - buildah push --retry 5 --retry-delay 10s ${BASE_IMAGE_PATH}/${ENVIRONMENT}:latest
